package io.github.tuguzd.restaurantapp.presentation.view.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme color
val md_theme_light_primary = Color(0xFF186d0b)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFa0f887)
val md_theme_light_onPrimaryContainer = Color(0xFF002200)
val md_theme_light_secondary = Color(0xFF0c6d35)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF9ff6b0)
val md_theme_light_onSecondaryContainer = Color(0xFF00210a)
val md_theme_light_tertiary = Color(0xFF006c4e)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF85f8cc)
val md_theme_light_onTertiaryContainer = Color(0xFF002115)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFfcfcf6)
val md_theme_light_onBackground = Color(0xFF1a1c19)
val md_theme_light_surface = Color(0xFFfcfcf6)
val md_theme_light_onSurface = Color(0xFF1a1c19)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFf1f1eb)
val md_theme_light_inverseSurface = Color(0xFF2e312c)
val md_theme_light_inversePrimary = Color(0xFF85db6e)
val md_theme_light_shadow = Color(0xFF000000)

// Dark theme color
val md_theme_dark_primary = Color(0xFF85db6e)
val md_theme_dark_onPrimary = Color(0xFF003a00)
val md_theme_dark_primaryContainer = Color(0xFF005300)
val md_theme_dark_onPrimaryContainer = Color(0xFFa0f887)
val md_theme_dark_secondary = Color(0xFF82d995)
val md_theme_dark_onSecondary = Color(0xFF003916)
val md_theme_dark_secondaryContainer = Color(0xFF005323)
val md_theme_dark_onSecondaryContainer = Color(0xFF9ff6b0)
val md_theme_dark_tertiary = Color(0xFF67dbb0)
val md_theme_dark_onTertiary = Color(0xFF003827)
val md_theme_dark_tertiaryContainer = Color(0xFF00513a)
val md_theme_dark_onTertiaryContainer = Color(0xFF85f8cc)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1a1c19)
val md_theme_dark_onBackground = Color(0xFFe2e3dc)
val md_theme_dark_surface = Color(0xFF1a1c19)
val md_theme_dark_onSurface = Color(0xFFe2e3dc)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c19)
val md_theme_dark_inverseSurface = Color(0xFFe2e3dc)
val md_theme_dark_inversePrimary = Color(0xFF186d0b)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)
